name: DEV CI Workflow

on:
  push:
  workflow_dispatch:

jobs:
  workflow-init:  
    uses: ./.github/workflows/workflow_init.yml
    secrets: inherit

  workflow-1:
    needs: workflow-init
    uses: ./.github/workflows/test_ci.yml
    secrets: inherit    

  workflow-2:     
    needs: workflow-init
    permissions:
     contents: write
    uses: ./.github/workflows/basic_ci_2.yml
    secrets: inherit

  workflow-metrics:     
    needs: [ workflow-1, workflow-2 ]
    if: always() 
    permissions:
     contents: write
    uses: ./.github/workflows/workflow_metrics.yml
    with:
      worfklow-1-status: ${{ needs.workflow-1.result }}
      workflow-2-status: ${{ needs.workflwo-2.result }}
    secrets: inherit
